config/routes.rb
PesquisaInstitucional::Application.routes.draw do
  get "relatorios", to: "relatorios#index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'principal#index'
  
  get '/ja_respondeu', to: 'principal#ja_respondeu', as: 'ja_respondeu'
  get 'login',  to: 'sessions#new',     as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :sessions
  resources :pesquisas
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/curso.rb
class Curso < ActiveRecord::Base
  belongs_to :instituicao
  attr_accessible :codigo, :nome, :instituicao, :instituicao_id
end

app/models/dimensao.rb
class Dimensao < ActiveRecord::Base
  belongs_to :pesquisa
  has_many :perguntas
  
  attr_accessible :nome, :ordem, :pesquisa, :pesquisa_id, :perguntas_attributes
  accepts_nested_attributes_for :perguntas
end

app/models/instituicao.rb
class Instituicao < ActiveRecord::Base
  attr_accessible :nome
  
  has_many :cursos
  
  def to_s
    nome
  end
end

app/models/pergunta.rb
class Pergunta < ActiveRecord::Base
  belongs_to :dimensao
  attr_accessible :nome, :ordem, :dimensao, :dimensao_id
  attr_accessor :resposta
end

app/models/pesquisa.rb
class Pesquisa < ActiveRecord::Base
  belongs_to :instituicao
  has_many :dimensoes
  
  attr_accessible :ano, :nome, :periodo, :dimensoes_attributes, :instituicao, :instituicao_id, :professor
  accepts_nested_attributes_for :dimensoes
end

app/models/resposta.rb
class Resposta < ActiveRecord::Base
  belongs_to :pergunta
  belongs_to :usuario
  attr_accessible :resposta, :pergunta_id, :usuario_id
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  attr_accessible :login, :nome
  
  validates_uniqueness_of :login
  has_many :respostas
  
  def aluno?
    login.length == 10
  end
  
  def ja_respondeu?(pesquisa)
    Resposta.where(:usuario_id => id).exists?
  end
  
  def curso
    puts Curso.all
    Curso.where(:codigo => login[3..5].to_i).first
  end
end

app/controllers/application_controller.rb
#encoding: utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery
  
private
  def usuario_logado
    @usuario_logado ||= Usuario.where(:login => session[:usuario_login]).first if session[:usuario_login]
  end
  helper_method :usuario_logado
  
  def conteudo_privado
    redirect_to login_url, alert: "Você precisa se identificar para poder responder a pesquisa" if usuario_logado.nil?
  end
end

app/controllers/pesquisas_controller.rb
class PesquisasController < ApplicationController
  def update
    pesquisa = params[:pesquisa]
    pesquisa[:dimensoes_attributes].each do |kd, dimensao|
      dimensao[:perguntas_attributes].each do |pd, pergunta|
        Resposta.create!(resposta: pergunta[:resposta], pergunta_id: pergunta[:id], usuario_id: usuario_logado.id)
      end
    end
  end
end

app/controllers/principal_controller.rb
class PrincipalController < ApplicationController
  before_filter :conteudo_privado
  
  def index
    if usuario_logado.aluno?
      @pesquisa = Pesquisa.where(:instituicao_id => usuario_logado.curso.instituicao).order("ano DESC, periodo DESC").first
      redirect_to action: "ja_respondeu" if usuario_logado.ja_respondeu?(@pesquisa)
    else
      @pesquisa = Pesquisa.where(:professor => true).order("ano DESC, periodo DESC").first
      redirect_to action: "ja_respondeu" if usuario_logado.ja_respondeu?(@pesquisa)
    end
  end
  
  def ja_respondeu
  end
end

app/controllers/relatorios_controller.rb
class RelatoriosController < ApplicationController
  def index
    @qtd_alunos      = Usuario.where(:id => Resposta.select("usuario_id").group("usuario_id")).where("length(login) = 10").count()
    @qtd_professores = Usuario.where(:id => Resposta.select("usuario_id").group("usuario_id")).where("length(login) <> 10").count()
    
    @qtd_alunos_facisa = qtd_por_instituicao('FACISA')
    @qtd_alunos_fcm    = qtd_por_instituicao('FCM')
    @qtd_alunos_esac   = qtd_por_instituicao('ESAC')
  end
  
  private 
  def qtd_por_instituicao(instituicao)
    total = 0
    Instituicao.where(:nome => instituicao).first.cursos.each do |curso|
      qtd = Usuario.where(:id => Resposta.select("usuario_id").group("usuario_id")).where("length(login) = 10").where("login like ?", "___#{curso.codigo}____").count()
      total += qtd if qtd
    end
    total
  end
  
  helper_method :qtd_por_curso
  def qtd_por_curso(curso)
    Usuario.where(:id => Resposta.select("usuario_id").group("usuario_id")).where("length(login) = 10").where("login like ?", "___#{curso.codigo}____").count()
  end
end

app/controllers/sessions_controller.rb
#encoding: utf-8
require 'net/ldap'

class SessionsController < ApplicationController
  def new
    
  end
  
  def create
    puts params
    if params[:login].blank?
      flash.alert = "Você deve informar o login"
      redirect_to action: :new
    elsif params[:senha].blank?
      flash.alert = "Você deve informar a senha"
      redirect_to action: :new, login: params[:login]
    else
      usuario = authenticate(params[:login], params[:senha])
      if usuario
        session[:usuario_login] = usuario.login
        redirect_to root_url, notice: "Seja bem vindo(a) #{usuario.nome}"
      else
        flash.alert = "Usuário e/ou senha não conferem"
        redirect_to action: :new, login: params[:login]
      end
    end
  end
  
  def destroy
    session[:usuario_login] = nil
    redirect_to root_url, notice: "Obrigado por participar de nossa pesquisa"
  end
  
  private
  def authenticate(login, senha)
    unless Rails.env.production?
      return Usuario.find(2) if login.length == 10
      return Usuario.find(1)
    end
    
    dominio = 'cesed.local'

    ldap = Net::LDAP.new
    ldap.host = '192.168.250.2'
    ldap.port = 389
    ldap.auth "#{login}@#{dominio}", senha

    if ldap.bind
      return Usuario.where(:login => login).first_or_create do |usuario|
        result = ldap.search(base: "DC=cesed,DC=local", 
                             filter: Net::LDAP::Filter.eq("samaccountname", login), 
                             attributes: %w[ displayName ], 
                             return_result:true)
        usuario.nome = result.first.displayName.first
      end
    end
    return nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pesquisas_helper.rb
module PesquisasHelper
end

app/helpers/principal_helper.rb
module PrincipalHelper
end

app/helpers/relatorios_helper.rb
module RelatoriosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9" lang="en">
:plain
  <!--[if gt IE 8] -->
%html{:lang => "en"}
  /<![endif]
  %head
    %meta{:charset => "utf-8"}/
    
    / Set the viewport width to device width for mobile
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    
    %title= content_for?(:title) ? yield(:title) : "CESED - Pesquisa Docente - 2013"
    
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/custom.modernizr" 
    = csrf_meta_tags
  %body
    / Header and Nav
    %nav{:class=>"top-bar"}
      %ul{:class=>"title-area"}
        / Title Area
        %li.name
          %h1
            %a{:href=>"#"} Pesquisa Institucional
      %section{:class=>"top-bar-section"}
        %ul.right
          %li.divider
          %li
            - if usuario_logado
              = link_to "#{usuario_logado.nome}, Sair", logout_path
            - else
              = link_to "Entrar", login_path
    / End Header and Nav
    
    / Main Grid Section
    .row
      - flash.each do |name, msg|
        - if msg.is_a?(String)
          %div{:class => "alert-box #{name == :notice ? "success" : "alert"}", :"data-alert" => true}
            = msg
            %a{:href => '#', :class => "close"} &times;
      = yield
    / End Grid Section
    
    / Footer
    %footer.row
      %div{:class=>"large-12 columns"}
        %hr
        .row
          %div{:class=>"large-6 columns"}
            %p &copy; Copyright LTI 2013, Todos os Direitos Reservados.
    
    = javascript_include_tag "application"

app/views/pesquisas/update.html.haml
.row
  %div{:class=>"panel callout radius"}
    %h1 Suas respostas foram registradas, obrigado.
    %hr
    %a{:href=>"http://www.cesed.br", :class=>"large button expand round success"} Voltar ao Site Principal

app/views/principal/index.html.haml
%h3= @pesquisa.nome
= simple_form_for @pesquisa do |f|
  = f.input :id, as: :hidden
  = f.simple_fields_for :dimensoes do |dimensao|
    = dimensao.input :id, as: :hidden
    .panel
      %h6= dimensao.object.nome
      %hr
      = dimensao.simple_fields_for :perguntas do |pergunta|
        .row
          %div{:class=>"small-2 columns"}
            = pergunta.input :id, as: :hidden
            = pergunta.input :resposta, collection: 0..5, as: :star_rating, label: false, error_html: { class: 'validation_error'}
          %div{:class=>"small-10 columns"}
            %label{:class=>"inline"}= pergunta.object.nome
  .row= f.submit 'Enviar Respostas', :class => 'large button expand round'
          

app/views/principal/ja_respondeu.html.haml
.row
  %div{:class=>"panel callout radius"}
    %h1 Obrigado, mas você já respondeu a nossa pesquisa.
    %hr
    %a{:href=>"http://www.cesed.br", :class=>"large button expand round success"} Voltar ao Site Principal

app/views/relatorios/index.html.erb
<h1>Acompanhamento das Respostas</h1>
<hr/>
<h3>Resultado Geral</h3>
<table>
  <thead>
    <tr>
      <th>Categoria</th>
      <th>Quantidade</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Alunos</td>
      <td><%= @qtd_alunos %></td>
    </tr>
    <tr>
      <td>Professores</td>
      <td><%= @qtd_professores %></td>
    </tr>
  </tbody>
</table>
<hr/>
<h3>Resultado por Instituição</h3>
<table>
  <thead>
    <tr>
      <th>Instituição</th>
      <th>Categoria</th>
      <th>Quantidade</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>FACISA</td>
      <td>Alunos</td>
      <td><%= @qtd_alunos_facisa %></td>
    </tr>
    <tr>
      <td>FCM</td>
      <td>Alunos</td>
      <td><%= @qtd_alunos_fcm %></td>
    </tr>
    <tr>
      <td>ESAC</td>
      <td>Alunos</td>
      <td><%= @qtd_alunos_esac %></td>
    </tr>
  </tbody>
</table>
<hr/>
<% Instituicao.find_each do |instituicao| %>
  <h3>Resultado por Curso: <%= instituicao.nome %></h3>
  <table>
    <thead>
      <tr>
        <th>Curso</th>
        <th>Quantidade</th>
      </tr>
    </thead>
    <tbody>
      <% instituicao.cursos.each do |curso| %>
        <tr>
          <td><%= curso.nome %></td>
          <td><%= qtd_por_curso(curso) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>